/* The words this window draws.
 *
 * They are asked for by key from `config_src/languages.json` through the same catalog the tray and the
 * egui window read, so a translation lives in exactly one file. The English map below is not a second
 * copy of the product's copy — it is what renders before the first reply arrives and what shows if a
 * key was never shipped, which is the failure mode worth being loud about. `ui_strings` resolves a
 * missing key to the catalog's own `(key) not found …` marker, so a dropped translation is visible on
 * screen instead of silently falling back to English in a Chinese install.
 */

/** Every key this window asks the catalog for. */
export const COPY_KEYS = [
  // Pre-existing: the tab bar and the footer, already translated for the egui window.
  "windui_tab_search",
  "windui_tab_oneday",
  "windui_tab_stat",
  "windui_tab_recording",
  "windui_tab_settings",
  "windui_tab_ai",
  "windui_footer_refresh",
  // New chrome for this window.
  "windui_web_brand",
  "windui_web_tagline",
  "windui_web_search_title",
  "windui_web_search_detail",
  "windui_web_keywords",
  "windui_web_keywords_hint",
  "windui_web_exclude",
  "windui_web_from",
  "windui_web_to",
  "windui_web_page_size",
  "windui_web_run",
  "windui_web_running",
  "windui_web_results",
  "windui_web_no_rows_title",
  "windui_web_no_rows_detail",
  "windui_web_no_index_title",
  "windui_web_no_index_detail",
  "windui_web_locate",
  "windui_web_play",
  "windui_web_play_stop",
  "windui_web_play_hint",
  "windui_web_play_stop_hint",
  "windui_web_play_loading",
  "windui_web_play_none",
  "windui_web_play_undecodable",
  "windui_web_play_transcoding",
  "windui_web_playing",
  "windui_web_play_back_to_moment",
  "windui_web_detail",
  "windui_web_close",
  "windui_web_deep_link_absent",
  "windui_web_title_none",
  "windui_web_oneday_title",
  "windui_web_oneday_detail",
  "windui_web_active_hours",
  "windui_web_titles",
  "windui_web_flags",
  "windui_web_strip",
  "windui_web_day_activity",
  "windui_web_rows",
  "oneday_text_flag_mark_help",
  "windui_web_unindexed",
  "windui_web_stat_title",
  "windui_web_stat_detail",
  "windui_web_lightbox",
  "windui_web_wordcloud",
  "windui_web_recording_title",
  "windui_web_recording_detail",
  "windui_web_settings_title",
  "windui_web_settings_detail",
  "windui_web_ai_title",
  "windui_web_ai_detail",
  // The original frame behind a row: the click's promise, its two waiting states, and where the
  // picture came from. The last two are what the `frame` command names back, so they are keys.
  // `windui_card_preview_hint` is the first step of that click — the card opens the row, the row's
  // picture opens the frame — and prev/next are the viewer's walk along the list it was opened from.
  "windui_card_preview_hint",
  "windui_frame_hint",
  "windui_frame_loading",
  "windui_frame_stored_only",
  "windui_frame_missing",
  "windui_frame_prev",
  "windui_frame_next",
  "windui_frame_from_screenshot",
  "windui_frame_from_video",
  "windui_web_save",
  "windui_web_saving",
  "windui_web_saved",
  "windui_web_save_blocked",
  "windui_web_ai_key_state",
  "windui_web_ai_clear_key",
  "windui_web_ai_test",
  "windui_web_ai_testing",
  "windui_web_ai_ready",
  "windui_web_bridge_title",
  "windui_web_bridge_url",
  "windui_web_monitors",
  "windui_web_loading",
  "windui_web_range_hint",
  // The literals this window used to paint straight from the source file. Each is a sentence the
  // English-only reader and the Chinese-only reader were not being given the same chance to read.
  "windui_web_boot_error_note",
  "windui_web_locale_row",
  "windui_web_recording_on",
  "windui_web_recording_off",
  "windui_web_error_title",
  "windui_web_retry",
  "windui_web_elapsed_ms",
  "stat.rail.open_picture",
  "stat.tile.hint",
  "windui_web_stat_day_tooltip",
  "windui_web_ai_key_kept",
  // The two maintenance buttons and the line that explains them, on the page that also names the hours
  // the pass is allowed to run in. The catalog has carried all three rows in `en`, `sc` and `ja` since
  // the buttons landed; this list was the one thing still stopping the window from asking for them, so
  // the buttons painted the not-found marker over their own English.
  "windui_web_maintain_now",
  "windui_web_maintain_stop",
  "windui_web_maintain_help",
  // The pass's own report, read off the file it publishes. One total bar and one row per leg —
  // `docs/adr/2026-09-30-the-organise-pass-runs-on-four-legs.md` §一 replaced "第 N 步 / 共 9 步" with
  // item counts, so there are no step labels here to ask for and nothing on screen is a fraction of a
  // second. The four leg names and their units are plain verb phrases: what that row is doing, and what
  // one of its items is.
  "windui_web_maintain_total_label",
  "windui_web_maintain_total",
  "windui_web_maintain_leg_count",
  "windui_web_maintain_left",
  "windui_web_maintain_waiting",
  "windui_web_maintain_leg_done",
  "windui_web_leg_text",
  "windui_web_leg_text_unit",
  "windui_web_leg_convert",
  "windui_web_leg_convert_unit",
  "windui_web_leg_ai",
  "windui_web_leg_ai_unit",
  "windui_web_leg_other",
  "windui_web_leg_other_unit",
  "windui_web_maintain_manual",
  "windui_web_maintain_scheduled",
  "windui_web_maintain_none",
  "windui_web_maintain_complete",
  "windui_web_maintain_stopped",
  "windui_web_maintain_failed",
  "windui_web_maintain_crashed",
  // The census beside the two buttons: what the deferred pass would pick up if it ran now.
  "windui_web_backlog_run",
  "windui_web_backlog_counting",
  "windui_web_backlog_note",
  "windui_web_backlog_text",
  "windui_web_backlog_nomask",
  "windui_web_backlog_convert",
  "windui_web_backlog_reindex",
  "windui_web_backlog_expire",
  "windui_web_backlog_previews",
  "windui_web_backlog_summaries",
  "windui_web_backlog_failed",
  // The four edges of the crop mask, which is a rectangle the user reads off a screen and not a
  // number line: the words are the only thing telling which slider belongs to which side. These are
  // upstream's own keys — the egui window's mask editor names the same four bands with the same four
  // rows, so the web window asks for those rows rather than writing a second word for the same edge.
  "set_text_top_padding",
  "set_text_right_padding",
  "set_text_bottom_padding",
  "set_text_left_padding",
  // The AI prompt editor: the seven templates, where each one's text came from, and what a trial sent.
  "ai.prompts.title",
  "ai.prompts.detail",
  "ai.prompts.box",
  "ai.prompts.box_hint",
  "ai.prompts.shipped",
  "ai.prompts.shipped_hint",
  "ai.prompts.slots",
  "ai.prompts.required_hint",
  "ai.prompts.file",
  "ai.prompts.restore",
  "ai.prompts.restore_hint",
  "ai.prompts.try",
  "ai.prompts.trying",
  "ai.prompts.try_hint",
  "ai.prompts.trial_chars",
  "ai.prompts.unsaved",
  "ai.prompts.none_title",
  "ai.prompts.none_detail",
  "ai.prompts.embedded_note",
  // The three `PromptOrigin`s, printed as a pill on every row by `ORIGINS` in `screens/Forms.tsx`.
  "ai.prompts.origin.user",
  "ai.prompts.origin.shipped",
  "ai.prompts.origin.embedded",
  // The rail's own picture-and-facts block. `rail.frame.*` are the four lines beside the frame;
  // `rail.ai_summary.*` are the stored paragraph and the five states it can be in, which are four
  // different facts about *checking* and must never be read as one fact about absence.
  "rail.frame.segment",
  "rail.frame.at_second",
  "rail.frame.file",
  "rail.frame.rowid",
  "rail.ai_summary.title",
  "rail.ai_summary.segment",
  "rail.ai_summary.window",
  "rail.ai_summary.frames",
  "rail.ai_summary.frames_count",
  "rail.ai_summary.chars",
  "rail.ai_summary.written_at",
  "rail.ai_summary.written_by",
  "rail.ai_summary.written_by_unknown",
  "rail.ai_summary.day",
  "rail.ai_summary.day_value",
  "rail.ai_summary.state",
  "rail.ai_summary.state.current",
  "rail.ai_summary.state.content_changed",
  "rail.ai_summary.state.prompt_changed",
  "rail.ai_summary.state.unindexed",
  "rail.ai_summary.state.unknown",
  "rail.ai_summary.state.other",
  "rail.ai_summary.none",
  "rail.ai_summary.failed",
  "rail.ai_summary.no_frame",
  // The day screen's summary block, including the three answers to "where did this count come from"
  // and the one line that keeps yesterday's paragraph from being read as today's.
  "day.summary.title",
  "day.summary.none",
  "day.summary.blank",
  "day.summary.unreadable",
  "day.summary.failed",
  "day.summary.partial",
  "day.summary.stale",
  "day.summary.written_at",
  "day.summary.written_at_missing",
  "day.summary.written_by",
  "day.summary.coverage",
  "day.summary.coverage_from",
  "day.summary.coverage.stored",
  "day.summary.coverage.index",
  "day.summary.coverage.unknown",
  "day.summary.gaps",
  "day.summary.gaps_list",
  "day.summary.periods",
  "day.summary.periods_none",
  "day.summary.fallback",
  "day.summary.fallback_missing",
];

export const FALLBACK: Record<string, string> = {
  windui_tab_search: "Search",
  windui_tab_oneday: "OneDay",
  windui_tab_stat: "Stat",
  windui_tab_recording: "Recording",
  windui_tab_settings: "Settings",
  windui_tab_ai: "AI",
  windui_footer_refresh: "Refresh",
  windui_web_brand: "Windrecorder",
  windui_web_tagline: "What the screen saw",
  windui_web_search_title: "Search",
  windui_web_search_detail: "Every indexed frame in the range you name.",
  windui_web_keywords: "Keywords",
  windui_web_keywords_hint: "All of them must appear. Shape-similar Chinese is expanded by the recorder's own table.",
  windui_web_exclude: "Exclude",
  windui_web_from: "From",
  windui_web_to: "To",
  windui_web_page_size: "Per page",
  windui_web_run: "Search",
  windui_web_running: "Searching",
  windui_web_results: "{count} of {total} hits",
  windui_web_no_rows_title: "Nothing in this range",
  windui_web_no_rows_detail: "The index answered, and there is no frame between those two dates. Widen the range, or clear the keywords.",
  windui_web_no_index_title: "This install has no index yet",
  windui_web_no_index_detail: "Nothing has been recorded into it, or the recorder has not closed a segment yet — rows land when a segment is written, not while it is being captured.",
  windui_web_locate: "Locate",
  windui_web_play: "Play",
  windui_web_play_stop: "Frame",
  windui_web_play_hint: "Watch the segment this row was taken from, inside the window, starting at this row's second",
  windui_web_play_stop_hint: "Stop the segment and go back to the single frame the index holds for this row",
  windui_web_play_loading: "opening the segment…",
  windui_web_play_none: "This row's segment is no longer on disk, so there is nothing to play. What shows here is the small preview the index stores.",
  windui_web_play_undecodable: "The file is there, and this window's player still refused it. Locate will hand it to a player you already have.",
  windui_web_play_transcoding: "This machine cannot decode {codec} in the window, so ffmpeg is making one copy it can. That happens once per segment.",
  windui_web_playing: "{name} · playing from {at}",
  windui_web_play_back_to_moment: "Back to this row",
  windui_web_detail: "Detail",
  windui_web_close: "Close",
  windui_web_deep_link_absent: "No deep link — the native recorder does not capture one.",
  windui_web_title_none: "No window title",
  windui_web_oneday_title: "OneDay",
  windui_web_oneday_detail: "One product day, beginning when the recorder says the day begins.",
  windui_web_active_hours: "Active hours",
  windui_web_titles: "Where the time went",
  windui_web_flags: "Marks",
  windui_web_strip: "The day, as a strip",
  windui_web_day_activity: "Recording density, one bar per six minutes",
  windui_web_rows: "{count} rows",
  oneday_text_flag_mark_help:
    "When you want to add a mark to an important meeting, emergency situation, certain live broadcast, game or movie viewing highlight moment, etc. to facilitate future review, you can add a mark to the present moment through the tray menu.",
  windui_web_unindexed: "A video on disk is not in the index yet.",
  windui_web_stat_title: "Stat",
  windui_web_stat_detail: "Rows per day and per month, counted from the index itself.",
  windui_web_lightbox: "Lightbox",
  windui_web_wordcloud: "Word cloud",
  windui_web_recording_title: "Recording",
  windui_web_recording_detail: "What the recorder captures, and how. Applied to the next segment.",
  windui_web_settings_title: "Settings",
  windui_web_settings_detail: "The keys these screens read. Nothing here is offered that the engine ignores.",
  windui_web_ai_title: "AI",
  windui_web_ai_detail: "The configuration windai reads, validated by windai's own rules.",
  windui_web_save: "Save",
  windui_web_saving: "Saving",
  windui_web_saved: "Written to {path}",
  windui_web_save_blocked: "Not saved — {count} problem(s)",
  windui_web_ai_key_state: "Stored key: {state}",
  windui_web_ai_clear_key: "Delete the stored key",
  windui_web_ai_test: "Test connection",
  windui_web_ai_testing: "Testing",
  windui_web_ai_ready: "Ready",
  windui_web_bridge_title: "MCP bridge",
  windui_web_bridge_url: "Paste this into your AI client",
  windui_web_monitors: "Monitors",
  windui_web_loading: "Loading",
  windui_web_range_hint: "Whole days, from {day} at 03:00.",
  // The picture behind a row. These render before the catalog answers, and the viewer's own caption is
  // read while a disk seek is still running, so a missing one here shows a raw key over a black box.
  windui_card_preview_hint: "Click to open this row",
  windui_frame_hint: "Click to open the original frame",
  windui_frame_loading: "reading the original frame…",
  windui_frame_stored_only: "the preview the index stores",
  windui_frame_missing:
    "No original frame is left on disk for this row: its screenshot slice has passed its retention window and its video is gone. What shows here is the small preview the index stores.",
  windui_frame_prev: "Previous frame",
  windui_frame_next: "Next frame",
  windui_frame_from_screenshot: "Original frame, from the screenshot cache",
  windui_frame_from_video: "Frame taken out of the recorded video at this moment",
  // Sentences this window used to hardcode.
  windui_web_boot_error_note:
    "The window opened, so the binary runs. What failed is this install's data layer — the message above is its own words, not a summary.",
  windui_web_locale_row: "locale {locale}",
  windui_web_recording_on: "recording · pid {pid}",
  windui_web_recording_off: "not recording",
  windui_web_error_title: "This could not be read",
  windui_web_retry: "Retry",
  windui_web_elapsed_ms: "{ms} ms",
  windui_web_stat_day_tooltip: "{date} · {count} rows · {hours} h",
  windui_web_ai_key_kept: "Leaving the key box empty keeps what is stored; this box is the only way to remove it.",
  // The maintenance pass's own report. These render before the catalog answers and on a key nobody
  // shipped, so they are the English the catalog is expected to carry — not a second vocabulary.
  // Counts of items only: no step numbers, and nothing that turns a second into a percentage or an
  // estimate of how long is left (the owner refused both).
  windui_web_maintain_total_label: "Organising",
  windui_web_maintain_total: "{done} / {total} items done",
  windui_web_maintain_leg_count: "{done} / {total} {unit}",
  windui_web_maintain_left: "{n} still to do",
  windui_web_maintain_waiting: "not started yet",
  windui_web_maintain_leg_done: "its own share is done",
  windui_web_leg_text: "Reading the screen text",
  windui_web_leg_text_unit: "pictures",
  windui_web_leg_convert: "Building the videos",
  windui_web_leg_convert_unit: "segments",
  windui_web_leg_ai: "AI summaries",
  windui_web_leg_ai_unit: "stretches",
  windui_web_leg_other: "The other tidying",
  windui_web_leg_other_unit: "items",
  windui_web_maintain_manual: "started by the button",
  windui_web_maintain_scheduled: "started by the clock",
  windui_web_maintain_none: "Nothing has organised this library yet.",
  windui_web_maintain_complete: "The last pass did every one of the {total} items it counted.",
  windui_web_maintain_stopped: "The last pass left off with {left} items still waiting for the next one.",
  windui_web_maintain_failed: "The last pass could not do its own work on this machine — the red row says what.",
  windui_web_maintain_crashed: "A pass ended without saying how.",
  // The census. Each line is one step's own dry-run answer, so the wording names what that step does
  // rather than a table nobody can map back to it.
  windui_web_backlog_run: "count what is waiting",
  windui_web_backlog_counting: "counting…",
  windui_web_backlog_note: "Counting reads the library and changes nothing. A pass running now makes these numbers smaller.",
  windui_web_backlog_text: "{n} rows have no text read off them yet",
  windui_web_backlog_nomask: "{n} of them have no masked frame, so nothing can be read from them",
  windui_web_backlog_convert: "{n} screenshot slices waiting to become video ({f} frames)",
  windui_web_backlog_reindex: "{n} recordings have never been indexed",
  windui_web_backlog_expire: "{n} segments to compress · {d} past their retention",
  windui_web_backlog_previews: "{n} rows to redraw at the width you set",
  windui_web_backlog_summaries: "{n} stretches have no summary",
  windui_web_backlog_failed: "The count did not finish: {error}",
  // Upstream's four mask-edge rows, with upstream's four Rust fallbacks. `commands.rs` resolves the same
  // keys with `text_or` and ships them in `field.edges`; these are what render on the row that says it
  // has no edges at all.
  set_text_top_padding: "Top",
  set_text_right_padding: "Right",
  set_text_bottom_padding: "Bottom",
  set_text_left_padding: "Left",
  // The AI prompt editor.
  "ai.prompts.title": "Prompt templates",
  "ai.prompts.detail": "The seven texts windai sends. Each is a file you can rewrite, and the text in force here is the text of the next request.",
  "ai.prompts.box": "In force",
  "ai.prompts.box_hint": "What the next request built from this template will send. Editing sends nothing; saving writes your own file.",
  "ai.prompts.shipped": "What this build ships",
  "ai.prompts.shipped_hint": "The default your override replaced, beside the words in use so a drift after an update can be read rather than remembered. Nothing here is sent from this box.",
  "ai.prompts.slots": "Placeholders",
  "ai.prompts.required_hint": "The marked ones carry the material itself. A template missing one is refused rather than saved.",
  "ai.prompts.file": "The file this text was read from, and the one a save writes",
  "ai.prompts.restore": "Restore the shipped text",
  "ai.prompts.restore_hint": "Delete your own file so this build's words answer again. Your text goes with it.",
  "ai.prompts.try": "Try",
  "ai.prompts.trying": "Asking",
  "ai.prompts.try_hint": "Send one real request to the endpoint above, built from what is in this box and not from the file. Nothing is stored: not this text, not the answer, not the key.",
  "ai.prompts.trial_chars": "{chars} characters left this machine",
  "ai.prompts.unsaved": "Not saved",
  "ai.prompts.none_title": "No prompt templates",
  "ai.prompts.none_detail": "The engine answered with an empty list, so this install has no registered templates to show and nothing here can be edited.",
  "ai.prompts.embedded_note":
    "At least one text below is answering from the copy compiled into the binary, because this install's shipped prompt files could not be read. Saving writes a real file, and that template stops reading the embedded copy.",
  "ai.prompts.origin.user": "Your file",
  "ai.prompts.origin.shipped": "This install's file",
  "ai.prompts.origin.embedded": "Built into the binary",
  // The rail's four lines beside the picture, and the stored paragraph with its five states.
  "rail.frame.segment": "Segment",
  "rail.frame.at_second": "At second",
  "rail.frame.file": "Month file",
  "rail.frame.rowid": "Row",
  "rail.ai_summary.title": "What the AI said about this moment",
  "rail.ai_summary.segment": "Stretch",
  "rail.ai_summary.window": "Window",
  "rail.ai_summary.frames": "Frames",
  "rail.ai_summary.frames_count": "{count} frames",
  "rail.ai_summary.chars": "Screen text",
  "rail.ai_summary.written_at": "Written",
  "rail.ai_summary.written_by": "Written by",
  "rail.ai_summary.written_by_unknown": "producer not named",
  "rail.ai_summary.day": "From day",
  "rail.ai_summary.day_value": "day {date}",
  "rail.ai_summary.state": "Still stands",
  "rail.ai_summary.state.current": "Current",
  "rail.ai_summary.state.content_changed": "No longer trustworthy: the screen text it was written from has changed since",
  "rail.ai_summary.state.prompt_changed": "No longer trustworthy: it was written under a different prompt than the one in force",
  "rail.ai_summary.state.unindexed": "Cannot be checked: this index holds no such stretch, so nothing vouches for it either way",
  "rail.ai_summary.state.unknown": "Cannot be checked: neither the index nor the file would answer",
  "rail.ai_summary.state.other": "Cannot be checked: the door reported a state this window does not know ({state})",
  "rail.ai_summary.none": "No stored paragraph covers this minute. That is not a claim that nothing was written worth saying — it says no run has written one for the stretch this row sits in.",
  "rail.ai_summary.failed": "Could not ask the index for this row's paragraph:",
  "rail.ai_summary.no_frame": "The index holds no row of this day inside the window that paragraph was written about, so there is no picture to open. The text stands by itself.",
  // The day screen's summary block.
  "day.summary.title": "What the AI said about this day",
  "day.summary.none": "No paragraph has been written for {date}.",
  "day.summary.blank": "The file for {date} is there and holds no text.",
  "day.summary.unreadable": "The file for {date} exists but could not be read.",
  "day.summary.failed": "Could not read this day's summaries:",
  "day.summary.partial": "Written over an incomplete day",
  "day.summary.stale": "No longer trustworthy",
  "day.summary.written_at": "Written",
  "day.summary.written_at_missing": "the file names no time",
  "day.summary.written_by": "Written by",
  "day.summary.coverage": "Stretches summarised",
  "day.summary.coverage_from": "Counted from",
  "day.summary.coverage.stored": "the day's own paragraph, as the writer claimed it",
  "day.summary.coverage.index": "the index, recounted here and now",
  "day.summary.coverage.unknown": "nothing: neither the paragraph nor the index could answer, so these zeroes count no such thing",
  "day.summary.gaps": "Stretches with no paragraph",
  "day.summary.gaps_list": "Not covered:",
  "day.summary.periods": "Stretch paragraphs",
  "day.summary.periods_none": "Nothing was written about any stretch of {date}.",
  "day.summary.fallback":
    "This is the newest paragraph there is, and it was written for {date}. It appears under {asked} only because {asked} has none of its own — it says nothing about {asked}.",
  "day.summary.fallback_missing": "Nothing has been read for {date} yet.",
  "stat.tile.hint": "Open this minute: the rail shows what was written about it, and the picture is one step away",
  "stat.rail.open_picture": "Open the picture",
};

export type Copy = Record<string, string>;

/** What the catalog says about a key no locale holds — `wind_base::i18n::missing`, word for word, so the
 *  one sentence for "this copy is missing" is not spelled two different ways by the two surfaces that
 *  have to say it. */
function missingKey(key: string): string {
  return `(${key}) not found in i18n, please feedback to contributors.`;
}

/**
 * Resolve a key, then fill `{named}` placeholders the way the catalog's own `formatted` does.
 *
 * A key neither the catalog nor the fallback map answers is not returned as itself. The older
 * `copy[key] ?? FALLBACK[key] ?? key` handed back the bare key, which renders as a dotted word no
 * screen ever shows on purpose and reads like copy — the silent half of the bug the catalog already
 * shouts about, since `COPY_KEYS` is what `ui_strings` is told to resolve and a key missing from it
 * never arrives as an answer at all. Both halves now fail in the catalog's own words.
 */
export function t(copy: Copy, key: string, args?: Record<string, string | number>): string {
  const template = copy[key] ?? FALLBACK[key];
  if (template === undefined) return missingKey(key);
  let text = template;
  if (args) {
    for (const [name, value] of Object.entries(args)) {
      text = text.split(`{${name}}`).join(String(value));
    }
  }
  return text;
}
